import Foundation

enum Translator {
    static let minimumCoverage: Double = 0.35

    private struct Token {
        let original: String
        let normalized: String
        let isWord: Bool
    }

    static func translate(_ text: String, into languageCode: String) -> TranslationOutcome {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else {
            return TranslationOutcome(translatedText: "", coverage: 0, unknownWords: [])
        }

        let tokens = tokenize(trimmed)
        var index = 0
        var pieces: [String] = []
        var matched = 0
        var total = 0
        var unknown: [String] = []

        while index < tokens.count {
            let token = tokens[index]
            if !token.isWord {
                pieces.append(token.original)
                index += 1
                continue
            }

            if let phrase = longestPhrase(from: tokens, at: index, language: languageCode) {
                pieces.append(applyCase(phrase.translated, like: token.original))
                matched += phrase.wordCount
                total += phrase.wordCount
                index += phrase.consumed
                continue
            }

            total += 1
            if let mapped = wordTable[token.normalized]?[languageCode] {
                pieces.append(applyCase(mapped, like: token.original))
                matched += 1
            } else {
                pieces.append(token.original)
                if !unknown.contains(where: { $0.caseInsensitiveCompare(token.original) == .orderedSame }) {
                    unknown.append(token.original)
                }
            }
            index += 1
        }

        let coverage = total == 0 ? 0 : Double(matched) / Double(total)
        return TranslationOutcome(
            translatedText: pieces.joined(),
            coverage: coverage,
            unknownWords: unknown
        )
    }

    private static func tokenize(_ text: String) -> [Token] {
        var tokens: [Token] = []
        var current = ""
        for character in text {
            if character.isLetter || character == "'" || character == "’" {
                current.append(character)
            } else {
                if !current.isEmpty {
                    tokens.append(wordToken(current))
                    current = ""
                }
                tokens.append(Token(original: String(character), normalized: String(character), isWord: false))
            }
        }
        if !current.isEmpty {
            tokens.append(wordToken(current))
        }
        return tokens
    }

    private static func wordToken(_ raw: String) -> Token {
        let normalized = raw
            .replacingOccurrences(of: "’", with: "'")
            .lowercased()
        return Token(original: raw, normalized: normalized, isWord: true)
    }

    private static func longestPhrase(from tokens: [Token], at start: Int, language: String) -> (translated: String, wordCount: Int, consumed: Int)? {
        for key in sortedPhraseKeys {
            let parts = key.split(separator: " ").map(String.init)
            guard let consumed = consume(parts, in: tokens, from: start) else { continue }
            guard let translated = phraseTable[key]?[language] else { continue }
            return (translated, parts.count, consumed)
        }
        return nil
    }

    private static func consume(_ parts: [String], in tokens: [Token], from start: Int) -> Int? {
        var cursor = start
        var matched = 0
        while matched < parts.count {
            guard cursor < tokens.count else { return nil }
            let token = tokens[cursor]
            if !token.isWord {
                if token.original == " " || token.original == "\n" || token.original == "\t" {
                    cursor += 1
                    continue
                }
                return nil
            }
            if token.normalized != parts[matched] {
                return nil
            }
            matched += 1
            cursor += 1
        }
        return cursor - start
    }

    private static func applyCase(_ translated: String, like original: String) -> String {
        guard let firstOriginal = original.first, let firstTranslated = translated.first else {
            return translated
        }
        let letters = original.filter { $0.isLetter }
        if letters.count > 1 && original.uppercased() == original {
            return translated.uppercased()
        }
        if firstOriginal.isUppercase {
            return String(firstTranslated).uppercased() + translated.dropFirst()
        }
        return translated
    }

    private static let sortedPhraseKeys: [String] = {
        phraseTable.keys.sorted {
            $0.split(separator: " ").count > $1.split(separator: " ").count
        }
    }()

    private static let phraseTable: [String: [String: String]] = {
        build(phraseRows)
    }()

    private static let wordTable: [String: [String: String]] = {
        build(wordRowsA + wordRowsB + wordRowsC)
    }()

    private static func build(_ rows: [(String, String, String, String, String)]) -> [String: [String: String]] {
        var table: [String: [String: String]] = [:]
        table.reserveCapacity(rows.count)
        for row in rows {
            table[row.0] = ["es": row.1, "fr": row.2, "de": row.3, "it": row.4]
        }
        return table
    }

    private static let phraseRows: [(String, String, String, String, String)] = [
        ("once upon a time", "érase una vez", "il était une fois", "es war einmal", "c'era una volta"),
        ("happily ever after", "felices para siempre", "ils vécurent heureux", "und sie lebten glücklich", "e vissero felici e contenti"),
        ("to be or not to be", "ser o no ser", "être ou ne pas être", "sein oder nicht sein", "essere o non essere"),
        ("all the world's a stage", "el mundo entero es un escenario", "le monde entier est un théâtre", "die ganze Welt ist eine Bühne", "tutto il mondo è un palcoscenico"),
        ("in the beginning", "en el principio", "au commencement", "am Anfang", "in principio"),
        ("all of a sudden", "de repente", "tout à coup", "plötzlich", "all'improvviso"),
        ("as a matter of fact", "de hecho", "en fait", "tatsächlich", "in effetti"),
        ("at the same time", "al mismo tiempo", "en même temps", "zur gleichen Zeit", "allo stesso tempo"),
        ("in the middle of", "en medio de", "au milieu de", "inmitten", "in mezzo a"),
        ("in front of", "delante de", "devant", "vor", "davanti a"),
        ("in spite of", "a pesar de", "malgré", "trotz", "nonostante"),
        ("in order to", "para", "afin de", "um zu", "al fine di"),
        ("in addition to", "además de", "en plus de", "zusätzlich zu", "oltre a"),
        ("as well as", "así como", "ainsi que", "sowie", "così come"),
        ("because of", "debido a", "à cause de", "wegen", "a causa di"),
        ("instead of", "en lugar de", "au lieu de", "anstatt", "invece di"),
        ("according to", "según", "selon", "laut", "secondo"),
        ("out of", "fuera de", "hors de", "aus", "fuori da"),
        ("such as", "como", "tel que", "wie zum Beispiel", "come"),
        ("rather than", "en lugar de", "plutôt que", "eher als", "piuttosto che"),
        ("even though", "aunque", "même si", "obwohl", "anche se"),
        ("as soon as", "tan pronto como", "dès que", "sobald", "non appena"),
        ("as long as", "mientras", "tant que", "solange", "finché"),
        ("so that", "para que", "afin que", "damit", "così che"),
        ("even if", "incluso si", "même si", "auch wenn", "anche se"),
        ("no longer", "ya no", "ne plus", "nicht mehr", "non più"),
        ("at last", "por fin", "enfin", "endlich", "finalmente"),
        ("at least", "al menos", "au moins", "wenigstens", "almeno"),
        ("for example", "por ejemplo", "par exemple", "zum Beispiel", "per esempio"),
        ("a lot of", "mucho", "beaucoup de", "viele", "molto"),
        ("a few", "unos pocos", "quelques", "ein paar", "alcuni"),
        ("a little", "un poco", "un peu", "ein wenig", "un poco"),
        ("each other", "el uno al otro", "l'un l'autre", "einander", "l'un l'altro"),
        ("of course", "por supuesto", "bien sûr", "natürlich", "naturalmente"),
        ("more than", "más que", "plus que", "mehr als", "più di"),
        ("less than", "menos que", "moins que", "weniger als", "meno di"),
        ("once more", "una vez más", "encore une fois", "noch einmal", "ancora una volta"),
        ("at night", "de noche", "la nuit", "bei Nacht", "di notte"),
        ("in the dark", "en la oscuridad", "dans le noir", "im Dunkeln", "nel buio"),
        ("the rest of", "el resto de", "le reste de", "der Rest von", "il resto di")
    ]

    private static let wordRowsA: [(String, String, String, String, String)] = [
        ("the", "el", "le", "der", "il"),
        ("a", "un", "un", "ein", "un"),
        ("an", "un", "un", "ein", "un"),
        ("and", "y", "et", "und", "e"),
        ("or", "o", "ou", "oder", "o"),
        ("but", "pero", "mais", "aber", "ma"),
        ("if", "si", "si", "wenn", "se"),
        ("then", "entonces", "alors", "dann", "allora"),
        ("than", "que", "que", "als", "di"),
        ("because", "porque", "parce que", "weil", "perché"),
        ("though", "aunque", "quoique", "obwohl", "benché"),
        ("although", "aunque", "bien que", "obwohl", "sebbene"),
        ("while", "mientras", "pendant que", "während", "mentre"),
        ("when", "cuando", "quand", "wenn", "quando"),
        ("where", "donde", "où", "wo", "dove"),
        ("what", "qué", "quoi", "was", "che"),
        ("who", "quién", "qui", "wer", "chi"),
        ("whom", "a quien", "qui", "wen", "chi"),
        ("whose", "cuyo", "dont", "wessen", "il cui"),
        ("which", "cual", "lequel", "welche", "quale"),
        ("why", "por qué", "pourquoi", "warum", "perché"),
        ("how", "cómo", "comment", "wie", "come"),
        ("of", "de", "de", "von", "di"),
        ("to", "a", "à", "zu", "a"),
        ("in", "en", "dans", "in", "in"),
        ("on", "en", "sur", "auf", "su"),
        ("at", "en", "à", "an", "a"),
        ("by", "por", "par", "von", "da"),
        ("for", "para", "pour", "für", "per"),
        ("from", "de", "de", "aus", "da"),
        ("with", "con", "avec", "mit", "con"),
        ("without", "sin", "sans", "ohne", "senza"),
        ("into", "en", "dans", "in", "in"),
        ("onto", "sobre", "sur", "auf", "su"),
        ("upon", "sobre", "sur", "auf", "su"),
        ("over", "sobre", "sur", "über", "sopra"),
        ("under", "bajo", "sous", "unter", "sotto"),
        ("above", "encima", "au-dessus", "über", "sopra"),
        ("below", "debajo", "au-dessous", "unter", "sotto"),
        ("between", "entre", "entre", "zwischen", "tra"),
        ("among", "entre", "parmi", "unter", "tra"),
        ("through", "a través", "à travers", "durch", "attraverso"),
        ("across", "a través", "à travers", "über", "attraverso"),
        ("against", "contra", "contre", "gegen", "contro"),
        ("about", "sobre", "sur", "über", "su"),
        ("around", "alrededor", "autour", "um", "intorno"),
        ("before", "antes", "avant", "vor", "prima"),
        ("after", "después", "après", "nach", "dopo"),
        ("during", "durante", "pendant", "während", "durante"),
        ("until", "hasta", "jusqu'à", "bis", "fino a"),
        ("since", "desde", "depuis", "seit", "da"),
        ("within", "dentro de", "au sein de", "innerhalb", "entro"),
        ("beyond", "más allá", "au-delà", "jenseits", "oltre"),
        ("near", "cerca", "près", "nahe", "vicino"),
        ("off", "fuera", "hors", "ab", "via"),
        ("up", "arriba", "en haut", "auf", "su"),
        ("down", "abajo", "en bas", "nieder", "giù"),
        ("out", "fuera", "dehors", "heraus", "fuori"),
        ("not", "no", "ne pas", "nicht", "non"),
        ("no", "no", "non", "nein", "no"),
        ("yes", "sí", "oui", "ja", "sì"),
        ("nor", "ni", "ni", "noch", "né"),
        ("yet", "aún", "encore", "noch", "ancora"),
        ("so", "así", "ainsi", "so", "così"),
        ("very", "muy", "très", "sehr", "molto"),
        ("too", "demasiado", "trop", "zu", "troppo"),
        ("also", "también", "aussi", "auch", "anche"),
        ("only", "solo", "seulement", "nur", "solo"),
        ("just", "apenas", "juste", "gerade", "appena"),
        ("even", "incluso", "même", "sogar", "anche"),
        ("still", "todavía", "encore", "immer noch", "ancora"),
        ("already", "ya", "déjà", "schon", "già"),
        ("always", "siempre", "toujours", "immer", "sempre"),
        ("never", "nunca", "jamais", "nie", "mai"),
        ("ever", "jamás", "jamais", "je", "mai"),
        ("often", "a menudo", "souvent", "oft", "spesso"),
        ("sometimes", "a veces", "parfois", "manchmal", "a volte"),
        ("seldom", "rara vez", "rarement", "selten", "raramente"),
        ("again", "otra vez", "encore", "wieder", "di nuovo"),
        ("here", "aquí", "ici", "hier", "qui"),
        ("there", "allí", "là", "dort", "lì"),
        ("now", "ahora", "maintenant", "jetzt", "ora"),
        ("soon", "pronto", "bientôt", "bald", "presto"),
        ("today", "hoy", "aujourd'hui", "heute", "oggi"),
        ("tomorrow", "mañana", "demain", "morgen", "domani"),
        ("yesterday", "ayer", "hier", "gestern", "ieri"),
        ("once", "una vez", "une fois", "einmal", "una volta"),
        ("twice", "dos veces", "deux fois", "zweimal", "due volte"),
        ("i", "yo", "je", "ich", "io"),
        ("me", "me", "moi", "mich", "mi"),
        ("my", "mi", "mon", "mein", "mio"),
        ("mine", "mío", "le mien", "meiner", "mio"),
        ("myself", "mí mismo", "moi-même", "mich selbst", "me stesso"),
        ("you", "tú", "tu", "du", "tu"),
        ("your", "tu", "ton", "dein", "tuo"),
        ("yours", "tuyo", "le tien", "deiner", "tuo"),
        ("yourself", "tú mismo", "toi-même", "dich selbst", "te stesso"),
        ("he", "él", "il", "er", "lui"),
        ("him", "él", "lui", "ihn", "lui"),
        ("his", "su", "son", "sein", "suo"),
        ("himself", "él mismo", "lui-même", "sich selbst", "se stesso"),
        ("she", "ella", "elle", "sie", "lei"),
        ("her", "su", "sa", "ihr", "sua"),
        ("hers", "suya", "la sienne", "ihrs", "sua"),
        ("herself", "ella misma", "elle-même", "sich selbst", "se stessa"),
        ("it", "ello", "il", "es", "esso"),
        ("its", "su", "son", "sein", "suo"),
        ("itself", "sí mismo", "lui-même", "sich selbst", "se stesso"),
        ("we", "nosotros", "nous", "wir", "noi"),
        ("us", "nosotros", "nous", "uns", "noi"),
        ("our", "nuestro", "notre", "unser", "nostro"),
        ("ours", "nuestro", "le nôtre", "unsers", "nostro"),
        ("ourselves", "nosotros mismos", "nous-mêmes", "uns selbst", "noi stessi"),
        ("they", "ellos", "ils", "sie", "loro"),
        ("them", "ellos", "eux", "sie", "loro"),
        ("their", "su", "leur", "ihr", "loro"),
        ("theirs", "suyo", "le leur", "ihrs", "loro"),
        ("themselves", "ellos mismos", "eux-mêmes", "sich selbst", "loro stessi"),
        ("this", "este", "ce", "dies", "questo"),
        ("that", "ese", "cela", "das", "quello"),
        ("these", "estos", "ces", "diese", "questi"),
        ("those", "esos", "ceux", "jene", "quelli"),
        ("one", "uno", "un", "eins", "uno"),
        ("two", "dos", "deux", "zwei", "due"),
        ("three", "tres", "trois", "drei", "tre"),
        ("four", "cuatro", "quatre", "vier", "quattro"),
        ("five", "cinco", "cinq", "fünf", "cinque"),
        ("six", "seis", "six", "sechs", "sei"),
        ("seven", "siete", "sept", "sieben", "sette"),
        ("eight", "ocho", "huit", "acht", "otto"),
        ("nine", "nueve", "neuf", "neun", "nove"),
        ("ten", "diez", "dix", "zehn", "dieci"),
        ("all", "todo", "tout", "alle", "tutto"),
        ("every", "cada", "chaque", "jede", "ogni"),
        ("each", "cada", "chaque", "jede", "ciascuno"),
        ("any", "cualquier", "n'importe quel", "irgendein", "qualsiasi"),
        ("some", "algunos", "quelques", "einige", "alcuni"),
        ("many", "muchos", "beaucoup", "viele", "molti"),
        ("much", "mucho", "beaucoup", "viel", "molto"),
        ("few", "pocos", "peu", "wenige", "pochi"),
        ("little", "poco", "peu", "wenig", "poco"),
        ("more", "más", "plus", "mehr", "più"),
        ("most", "la mayoría", "le plus", "meist", "la maggior parte"),
        ("other", "otro", "autre", "ander", "altro"),
        ("another", "otro", "un autre", "ein anderer", "un altro"),
        ("same", "mismo", "même", "gleich", "stesso"),
        ("own", "propio", "propre", "eigen", "proprio"),
        ("such", "tal", "tel", "solch", "tale"),
        ("both", "ambos", "tous les deux", "beide", "entrambi"),
        ("either", "cualquiera", "l'un ou l'autre", "entweder", "o l'uno o l'altro"),
        ("neither", "ninguno", "ni l'un ni l'autre", "weder", "nessuno dei due"),
        ("is", "es", "est", "ist", "è"),
        ("am", "soy", "suis", "bin", "sono"),
        ("are", "son", "sont", "sind", "sono"),
        ("was", "era", "était", "war", "era"),
        ("were", "eran", "étaient", "waren", "erano"),
        ("be", "ser", "être", "sein", "essere"),
        ("been", "sido", "été", "gewesen", "stato"),
        ("being", "siendo", "étant", "seiend", "essendo"),
        ("have", "tener", "avoir", "haben", "avere"),
        ("has", "tiene", "a", "hat", "ha"),
        ("had", "tenía", "avait", "hatte", "aveva"),
        ("do", "hacer", "faire", "tun", "fare"),
        ("does", "hace", "fait", "tut", "fa"),
        ("did", "hizo", "fit", "tat", "fece"),
        ("done", "hecho", "fait", "getan", "fatto"),
        ("will", "va a", "va", "wird", "sarà"),
        ("would", "haría", "ferait", "würde", "farebbe"),
        ("can", "puede", "peut", "kann", "può"),
        ("could", "podría", "pourrait", "könnte", "potrebbe"),
        ("should", "debería", "devrait", "sollte", "dovrebbe"),
        ("shall", "deberá", "devra", "soll", "dovrà"),
        ("may", "puede", "peut", "mag", "può"),
        ("might", "podría", "pourrait", "könnte", "potrebbe"),
        ("must", "debe", "doit", "muss", "deve"),
        ("let", "deja", "laisse", "lass", "lascia"),
        ("i'm", "soy", "je suis", "ich bin", "sono"),
        ("you're", "eres", "tu es", "du bist", "sei"),
        ("he's", "él es", "il est", "er ist", "egli è"),
        ("she's", "ella es", "elle est", "sie ist", "lei è"),
        ("it's", "es", "c'est", "es ist", "è"),
        ("we're", "somos", "nous sommes", "wir sind", "siamo"),
        ("they're", "son", "ils sont", "sie sind", "sono"),
        ("i've", "he", "j'ai", "ich habe", "ho"),
        ("you've", "has", "tu as", "du hast", "hai"),
        ("we've", "hemos", "nous avons", "wir haben", "abbiamo"),
        ("they've", "han", "ils ont", "sie haben", "hanno"),
        ("i'll", "voy a", "je vais", "ich werde", "farò"),
        ("you'll", "vas a", "tu vas", "du wirst", "farai"),
        ("he'll", "él va a", "il va", "er wird", "farà"),
        ("she'll", "ella va a", "elle va", "sie wird", "farà"),
        ("we'll", "vamos a", "nous allons", "wir werden", "faremo"),
        ("they'll", "van a", "ils vont", "sie werden", "faranno"),
        ("i'd", "yo", "je", "ich", "io"),
        ("you'd", "tú", "tu", "du", "tu"),
        ("he'd", "él", "il", "er", "lui"),
        ("she'd", "ella", "elle", "sie", "lei"),
        ("we'd", "nosotros", "nous", "wir", "noi"),
        ("they'd", "ellos", "ils", "sie", "loro"),
        ("don't", "no", "ne pas", "nicht", "non"),
        ("doesn't", "no", "ne pas", "nicht", "non"),
        ("didn't", "no", "ne pas", "nicht", "non"),
        ("can't", "no puede", "ne peut pas", "kann nicht", "non può"),
        ("cannot", "no puede", "ne peut pas", "kann nicht", "non può"),
        ("won't", "no", "ne va pas", "wird nicht", "non"),
        ("wouldn't", "no", "ne ferait pas", "würde nicht", "non"),
        ("couldn't", "no pudo", "ne pouvait pas", "konnte nicht", "non poteva"),
        ("shouldn't", "no debería", "ne devrait pas", "sollte nicht", "non dovrebbe"),
        ("isn't", "no es", "n'est pas", "ist nicht", "non è"),
        ("aren't", "no son", "ne sont pas", "sind nicht", "non sono"),
        ("wasn't", "no era", "n'était pas", "war nicht", "non era"),
        ("weren't", "no eran", "n'étaient pas", "waren nicht", "non erano"),
        ("haven't", "no he", "n'ai pas", "habe nicht", "non ho"),
        ("hasn't", "no ha", "n'a pas", "hat nicht", "non ha"),
        ("hadn't", "no había", "n'avait pas", "hatte nicht", "non aveva"),
        ("that's", "eso es", "c'est", "das ist", "è"),
        ("there's", "hay", "il y a", "es gibt", "c'è"),
        ("here's", "aquí está", "voici", "hier ist", "ecco"),
        ("what's", "qué es", "qu'est-ce", "was ist", "che cos'è"),
        ("who's", "quién es", "qui est", "wer ist", "chi è"),
        ("let's", "vamos", "allons", "lass uns", "andiamo"),
        ("o", "oh", "ô", "o", "o"),
        ("oh", "oh", "oh", "oh", "oh"),
        ("ah", "ah", "ah", "ach", "ah"),
        ("call", "llama", "appelle", "rufe", "chiama"),
        ("come", "ven", "viens", "komm", "vieni"),
        ("go", "ve", "va", "geh", "vai"),
        ("went", "fue", "alla", "ging", "andò"),
        ("gone", "ido", "allé", "gegangen", "andato")
    ]

    private static let wordRowsB: [(String, String, String, String, String)] = [
        ("see", "ver", "voir", "sehen", "vedere"),
        ("saw", "vio", "vit", "sah", "vide"),
        ("seen", "visto", "vu", "gesehen", "visto"),
        ("look", "mira", "regarde", "schau", "guarda"),
        ("hear", "oír", "entendre", "hören", "udire"),
        ("heard", "oyó", "entendit", "hörte", "udì"),
        ("speak", "hablar", "parler", "sprechen", "parlare"),
        ("said", "dijo", "dit", "sagte", "disse"),
        ("say", "decir", "dire", "sagen", "dire"),
        ("tell", "contar", "raconter", "erzählen", "dire"),
        ("told", "contó", "raconta", "erzählte", "disse"),
        ("know", "saber", "savoir", "wissen", "sapere"),
        ("knew", "sabía", "savait", "wusste", "sapeva"),
        ("known", "conocido", "connu", "bekannt", "conosciuto"),
        ("think", "pensar", "penser", "denken", "pensare"),
        ("thought", "pensó", "pensa", "dachte", "pensò"),
        ("feel", "sentir", "sentir", "fühlen", "sentire"),
        ("felt", "sintió", "sentit", "fühlte", "sentì"),
        ("love", "amar", "aimer", "lieben", "amare"),
        ("loved", "amado", "aimé", "geliebt", "amato"),
        ("live", "vivir", "vivre", "leben", "vivere"),
        ("lived", "vivió", "vécut", "lebte", "visse"),
        ("die", "morir", "mourir", "sterben", "morire"),
        ("died", "murió", "mourut", "starb", "morì"),
        ("give", "dar", "donner", "geben", "dare"),
        ("gave", "dio", "donna", "gab", "diede"),
        ("given", "dado", "donné", "gegeben", "dato"),
        ("take", "tomar", "prendre", "nehmen", "prendere"),
        ("took", "tomó", "prit", "nahm", "prese"),
        ("taken", "tomado", "pris", "genommen", "preso"),
        ("find", "encontrar", "trouver", "finden", "trovare"),
        ("found", "encontró", "trouva", "fand", "trovò"),
        ("lose", "perder", "perdre", "verlieren", "perdere"),
        ("lost", "perdido", "perdu", "verloren", "perduto"),
        ("keep", "guardar", "garder", "behalten", "tenere"),
        ("kept", "guardó", "garda", "behielt", "tenne"),
        ("make", "hacer", "faire", "machen", "fare"),
        ("made", "hecho", "fait", "gemacht", "fatto"),
        ("become", "volverse", "devenir", "werden", "diventare"),
        ("became", "se volvió", "devint", "wurde", "divenne"),
        ("leave", "dejar", "laisser", "lassen", "lasciare"),
        ("left", "dejó", "laissa", "ließ", "lasciò"),
        ("remain", "permanecer", "rester", "bleiben", "restare"),
        ("wait", "esperar", "attendre", "warten", "aspettare"),
        ("walk", "caminar", "marcher", "gehen", "camminare"),
        ("run", "correr", "courir", "laufen", "correre"),
        ("stand", "estar de pie", "se tenir", "stehen", "stare"),
        ("stood", "se levantó", "se tint", "stand", "stette"),
        ("sit", "sentarse", "s'asseoir", "sitzen", "sedere"),
        ("sat", "se sentó", "s'assit", "saß", "sedette"),
        ("lie", "yacer", "gésir", "liegen", "giacere"),
        ("lay", "yacía", "gisait", "lag", "giaceva"),
        ("sleep", "dormir", "dormir", "schlafen", "dormire"),
        ("dream", "soñar", "rêver", "träumen", "sognare"),
        ("dreamed", "soñó", "rêva", "träumte", "sognò"),
        ("dreamt", "soñó", "rêva", "träumte", "sognò"),
        ("wake", "despertar", "réveiller", "wecken", "svegliare"),
        ("remember", "recordar", "se souvenir", "erinnern", "ricordare"),
        ("forget", "olvidar", "oublier", "vergessen", "dimenticare"),
        ("forgot", "olvidó", "oublia", "vergaß", "dimenticò"),
        ("begin", "comenzar", "commencer", "beginnen", "cominciare"),
        ("began", "comenzó", "commença", "begann", "cominciò"),
        ("begun", "comenzado", "commencé", "begonnen", "cominciato"),
        ("end", "terminar", "finir", "enden", "finire"),
        ("open", "abrir", "ouvrir", "öffnen", "aprire"),
        ("close", "cerrar", "fermer", "schließen", "chiudere"),
        ("bring", "traer", "apporter", "bringen", "portare"),
        ("brought", "trajo", "apporta", "brachte", "portò"),
        ("hold", "sostener", "tenir", "halten", "tenere"),
        ("held", "sostuvo", "tint", "hielt", "tenne"),
        ("fall", "caer", "tomber", "fallen", "cadere"),
        ("fell", "cayó", "tomba", "fiel", "cadde"),
        ("fallen", "caído", "tombé", "gefallen", "caduto"),
        ("rise", "elevarse", "s'élever", "steigen", "sorgere"),
        ("rose", "se elevó", "s'éleva", "stieg", "sorse"),
        ("ask", "preguntar", "demander", "fragen", "chiedere"),
        ("answer", "responder", "répondre", "antworten", "rispondere"),
        ("seek", "buscar", "chercher", "suchen", "cercare"),
        ("sought", "buscó", "chercha", "suchte", "cercò"),
        ("follow", "seguir", "suivre", "folgen", "seguire"),
        ("lead", "guiar", "mener", "führen", "guidare"),
        ("led", "guió", "mena", "führte", "guidò"),
        ("pass", "pasar", "passer", "passieren", "passare"),
        ("turn", "girar", "tourner", "wenden", "girare"),
        ("return", "volver", "revenir", "zurückkehren", "ritornare"),
        ("enter", "entrar", "entrer", "eintreten", "entrare"),
        ("appear", "aparecer", "apparaître", "erscheinen", "apparire"),
        ("seem", "parecer", "sembler", "scheinen", "sembrare"),
        ("become", "volverse", "devenir", "werden", "diventare"),
        ("want", "querer", "vouloir", "wollen", "volere"),
        ("need", "necesitar", "avoir besoin", "brauchen", "avere bisogno"),
        ("try", "intentar", "essayer", "versuchen", "provare"),
        ("hope", "esperar", "espérer", "hoffen", "sperare"),
        ("fear", "temer", "craindre", "fürchten", "temere"),
        ("wish", "desear", "souhaiter", "wünschen", "desiderare"),
        ("believe", "creer", "croire", "glauben", "credere"),
        ("understand", "entender", "comprendre", "verstehen", "capire"),
        ("read", "leer", "lire", "lesen", "leggere"),
        ("write", "escribir", "écrire", "schreiben", "scrivere"),
        ("wrote", "escribió", "écrivit", "schrieb", "scrisse"),
        ("written", "escrito", "écrit", "geschrieben", "scritto"),
        ("sing", "cantar", "chanter", "singen", "cantare"),
        ("sung", "cantado", "chanté", "gesungen", "cantato"),
        ("cry", "llorar", "pleurer", "weinen", "piangere"),
        ("laugh", "reír", "rire", "lachen", "ridere"),
        ("smile", "sonreír", "sourire", "lächeln", "sorridere"),
        ("kiss", "besar", "embrasser", "küssen", "baciare"),
        ("touch", "tocar", "toucher", "berühren", "toccare"),
        ("watch", "observar", "regarder", "betrachten", "guardare"),
        ("break", "romper", "casser", "brechen", "rompere"),
        ("broke", "rompió", "cassa", "brach", "ruppe"),
        ("broken", "roto", "cassé", "gebrochen", "rotto"),
        ("build", "construir", "construire", "bauen", "costruire"),
        ("built", "construyó", "construit", "baute", "costruì"),
        ("grow", "crecer", "grandir", "wachsen", "crescere"),
        ("grew", "creció", "grandit", "wuchs", "crebbe"),
        ("grown", "crecido", "grandi", "gewachsen", "cresciuto"),
        ("change", "cambiar", "changer", "ändern", "cambiare"),
        ("move", "mover", "bouger", "bewegen", "muovere"),
        ("stay", "quedarse", "rester", "bleiben", "restare"),
        ("hide", "esconder", "cacher", "verbergen", "nascondere"),
        ("hidden", "escondido", "caché", "verborgen", "nascosto"),
        ("show", "mostrar", "montrer", "zeigen", "mostrare"),
        ("shown", "mostrado", "montré", "gezeigt", "mostrato"),
        ("man", "hombre", "homme", "Mann", "uomo"),
        ("woman", "mujer", "femme", "Frau", "donna"),
        ("child", "niño", "enfant", "Kind", "bambino"),
        ("children", "niños", "enfants", "Kinder", "bambini"),
        ("boy", "niño", "garçon", "Junge", "ragazzo"),
        ("girl", "niña", "fille", "Mädchen", "ragazza"),
        ("people", "gente", "gens", "Leute", "gente"),
        ("friend", "amigo", "ami", "Freund", "amico"),
        ("father", "padre", "père", "Vater", "padre"),
        ("mother", "madre", "mère", "Mutter", "madre"),
        ("son", "hijo", "fils", "Sohn", "figlio"),
        ("daughter", "hija", "fille", "Tochter", "figlia"),
        ("brother", "hermano", "frère", "Bruder", "fratello"),
        ("sister", "hermana", "sœur", "Schwester", "sorella"),
        ("king", "rey", "roi", "König", "re"),
        ("queen", "reina", "reine", "Königin", "regina"),
        ("lord", "señor", "seigneur", "Herr", "signore"),
        ("lady", "dama", "dame", "Dame", "dama"),
        ("soul", "alma", "âme", "Seele", "anima"),
        ("heart", "corazón", "cœur", "Herz", "cuore"),
        ("mind", "mente", "esprit", "Geist", "mente"),
        ("life", "vida", "vie", "Leben", "vita"),
        ("death", "muerte", "mort", "Tod", "morte"),
        ("time", "tiempo", "temps", "Zeit", "tempo"),
        ("world", "mundo", "monde", "Welt", "mondo"),
        ("earth", "tierra", "terre", "Erde", "terra"),
        ("heaven", "cielo", "ciel", "Himmel", "cielo"),
        ("sky", "cielo", "ciel", "Himmel", "cielo"),
        ("sun", "sol", "soleil", "Sonne", "sole"),
        ("moon", "luna", "lune", "Mond", "luna"),
        ("star", "estrella", "étoile", "Stern", "stella"),
        ("stars", "estrellas", "étoiles", "Sterne", "stelle"),
        ("night", "noche", "nuit", "Nacht", "notte"),
        ("day", "día", "jour", "Tag", "giorno"),
        ("days", "días", "jours", "Tage", "giorni"),
        ("morning", "mañana", "matin", "Morgen", "mattina"),
        ("evening", "tarde", "soir", "Abend", "sera"),
        ("light", "luz", "lumière", "Licht", "luce"),
        ("dark", "oscuro", "sombre", "dunkel", "scuro"),
        ("darkness", "oscuridad", "obscurité", "Dunkelheit", "oscurità"),
        ("shadow", "sombra", "ombre", "Schatten", "ombra"),
        ("fire", "fuego", "feu", "Feuer", "fuoco"),
        ("water", "agua", "eau", "Wasser", "acqua"),
        ("sea", "mar", "mer", "Meer", "mare"),
        ("ocean", "océano", "océan", "Ozean", "oceano"),
        ("wind", "viento", "vent", "Wind", "vento"),
        ("air", "aire", "air", "Luft", "aria"),
        ("rain", "lluvia", "pluie", "Regen", "pioggia"),
        ("snow", "nieve", "neige", "Schnee", "neve"),
        ("stone", "piedra", "pierre", "Stein", "pietra"),
        ("tree", "árbol", "arbre", "Baum", "albero"),
        ("flower", "flor", "fleur", "Blume", "fiore"),
        ("garden", "jardín", "jardin", "Garten", "giardino"),
        ("house", "casa", "maison", "Haus", "casa"),
        ("home", "hogar", "foyer", "Heim", "casa"),
        ("door", "puerta", "porte", "Tür", "porta"),
        ("window", "ventana", "fenêtre", "Fenster", "finestra"),
        ("room", "habitación", "chambre", "Zimmer", "stanza"),
        ("road", "camino", "route", "Straße", "strada"),
        ("path", "sendero", "chemin", "Pfad", "sentiero"),
        ("way", "camino", "chemin", "Weg", "via"),
        ("place", "lugar", "lieu", "Ort", "luogo"),
        ("land", "tierra", "terre", "Land", "terra"),
        ("city", "ciudad", "ville", "Stadt", "città"),
        ("town", "pueblo", "ville", "Stadt", "città"),
        ("country", "país", "pays", "Land", "paese"),
        ("book", "libro", "livre", "Buch", "libro"),
        ("page", "página", "page", "Seite", "pagina"),
        ("word", "palabra", "mot", "Wort", "parola"),
        ("words", "palabras", "mots", "Worte", "parole"),
        ("story", "historia", "histoire", "Geschichte", "storia"),
        ("tale", "cuento", "conte", "Erzählung", "racconto"),
        ("letter", "carta", "lettre", "Brief", "lettera"),
        ("name", "nombre", "nom", "Name", "nome"),
        ("voice", "voz", "voix", "Stimme", "voce"),
        ("silence", "silencio", "silence", "Stille", "silenzio"),
        ("sound", "sonido", "son", "Klang", "suono"),
        ("song", "canción", "chanson", "Lied", "canzone"),
        ("music", "música", "musique", "Musik", "musica"),
        ("eye", "ojo", "œil", "Auge", "occhio"),
        ("eyes", "ojos", "yeux", "Augen", "occhi"),
        ("tear", "lágrima", "larme", "Träne", "lacrima"),
        ("tears", "lágrimas", "larmes", "Tränen", "lacrime"),
        ("hand", "mano", "main", "Hand", "mano"),
        ("hands", "manos", "mains", "Hände", "mani"),
        ("face", "rostro", "visage", "Gesicht", "volto"),
        ("head", "cabeza", "tête", "Kopf", "testa"),
        ("blood", "sangre", "sang", "Blut", "sangue"),
        ("body", "cuerpo", "corps", "Körper", "corpo"),
        ("truth", "verdad", "vérité", "Wahrheit", "verità"),
        ("lie", "mentira", "mensonge", "Lüge", "bugia"),
        ("beauty", "belleza", "beauté", "Schönheit", "bellezza"),
        ("nature", "naturaleza", "nature", "Natur", "natura"),
        ("fate", "destino", "destin", "Schicksal", "destino"),
        ("fortune", "fortuna", "fortune", "Glück", "fortuna"),
        ("chance", "azar", "hasard", "Zufall", "caso"),
        ("hope", "esperanza", "espoir", "Hoffnung", "speranza"),
        ("fear", "miedo", "peur", "Furcht", "paura"),
        ("joy", "alegría", "joie", "Freude", "gioia"),
        ("sorrow", "pena", "chagrin", "Kummer", "dolore"),
        ("grief", "duelo", "deuil", "Trauer", "lutto"),
        ("pain", "dolor", "douleur", "Schmerz", "dolore"),
        ("peace", "paz", "paix", "Frieden", "pace"),
        ("war", "guerra", "guerre", "Krieg", "guerra"),
        ("power", "poder", "pouvoir", "Macht", "potere"),
        ("freedom", "libertad", "liberté", "Freiheit", "libertà")
    ]

    private static let wordRowsC: [(String, String, String, String, String)] = [
        ("justice", "justicia", "justice", "Gerechtigkeit", "giustizia"),
        ("honor", "honor", "honneur", "Ehre", "onore"),
        ("honour", "honor", "honneur", "Ehre", "onore"),
        ("pride", "orgullo", "fierté", "Stolz", "orgoglio"),
        ("shame", "vergüenza", "honte", "Scham", "vergogna"),
        ("secret", "secreto", "secret", "Geheimnis", "segreto"),
        ("memory", "memoria", "mémoire", "Erinnerung", "memoria"),
        ("dream", "sueño", "rêve", "Traum", "sogno"),
        ("dreams", "sueños", "rêves", "Träume", "sogni"),
        ("sleep", "sueño", "sommeil", "Schlaf", "sonno"),
        ("deathless", "inmortal", "immortel", "unsterblich", "immortale"),
        ("forever", "para siempre", "pour toujours", "für immer", "per sempre"),
        ("nothing", "nada", "rien", "nichts", "niente"),
        ("something", "algo", "quelque chose", "etwas", "qualcosa"),
        ("everything", "todo", "tout", "alles", "tutto"),
        ("someone", "alguien", "quelqu'un", "jemand", "qualcuno"),
        ("anyone", "cualquiera", "n'importe qui", "jemand", "chiunque"),
        ("everyone", "todos", "tout le monde", "jeder", "tutti"),
        ("nobody", "nadie", "personne", "niemand", "nessuno"),
        ("good", "bueno", "bon", "gut", "buono"),
        ("great", "gran", "grand", "groß", "grande"),
        ("small", "pequeño", "petit", "klein", "piccolo"),
        ("old", "viejo", "vieux", "alt", "vecchio"),
        ("young", "joven", "jeune", "jung", "giovane"),
        ("new", "nuevo", "nouveau", "neu", "nuovo"),
        ("long", "largo", "long", "lang", "lungo"),
        ("short", "corto", "court", "kurz", "corto"),
        ("high", "alto", "haut", "hoch", "alto"),
        ("low", "bajo", "bas", "niedrig", "basso"),
        ("deep", "profundo", "profond", "tief", "profondo"),
        ("far", "lejos", "loin", "weit", "lontano"),
        ("near", "cerca", "proche", "nah", "vicino"),
        ("full", "lleno", "plein", "voll", "pieno"),
        ("empty", "vacío", "vide", "leer", "vuoto"),
        ("true", "verdadero", "vrai", "wahr", "vero"),
        ("false", "falso", "faux", "falsch", "falso"),
        ("right", "correcto", "juste", "richtig", "giusto"),
        ("wrong", "equivocado", "faux", "falsch", "sbagliato"),
        ("happy", "feliz", "heureux", "glücklich", "felice"),
        ("sad", "triste", "triste", "traurig", "triste"),
        ("alone", "solo", "seul", "allein", "solo"),
        ("lonely", "solitario", "solitaire", "einsam", "solitario"),
        ("quiet", "silencioso", "calme", "still", "quieto"),
        ("silent", "silencioso", "silencieux", "still", "silenzioso"),
        ("soft", "suave", "doux", "weich", "morbido"),
        ("hard", "duro", "dur", "hart", "duro"),
        ("cold", "frío", "froid", "kalt", "freddo"),
        ("warm", "cálido", "chaud", "warm", "caldo"),
        ("hot", "caliente", "chaud", "heiß", "caldo"),
        ("bright", "brillante", "brillant", "hell", "luminoso"),
        ("pale", "pálido", "pâle", "blass", "pallido"),
        ("golden", "dorado", "doré", "golden", "dorato"),
        ("wild", "salvaje", "sauvage", "wild", "selvaggio"),
        ("gentle", "gentil", "doux", "sanft", "gentile"),
        ("kind", "amable", "gentil", "freundlich", "gentile"),
        ("cruel", "cruel", "cruel", "grausam", "crudele"),
        ("brave", "valiente", "brave", "tapfer", "coraggioso"),
        ("wise", "sabio", "sage", "weise", "saggio"),
        ("foolish", "necio", "fou", "töricht", "folle"),
        ("poor", "pobre", "pauvre", "arm", "povero"),
        ("rich", "rico", "riche", "reich", "ricco"),
        ("free", "libre", "libre", "frei", "libero"),
        ("lost", "perdido", "perdu", "verloren", "perduto"),
        ("hidden", "oculto", "caché", "verborgen", "nascosto"),
        ("unknown", "desconocido", "inconnu", "unbekannt", "sconosciuto"),
        ("certain", "cierto", "certain", "gewiss", "certo"),
        ("possible", "posible", "possible", "möglich", "possibile"),
        ("impossible", "imposible", "impossible", "unmöglich", "impossibile"),
        ("beautiful", "hermoso", "beau", "schön", "bello"),
        ("fair", "bello", "beau", "schön", "bello"),
        ("dark", "oscuro", "sombre", "dunkel", "scuro"),
        ("sweet", "dulce", "doux", "süß", "dolce"),
        ("bitter", "amargo", "amer", "bitter", "amaro"),
        ("last", "último", "dernier", "letzte", "ultimo"),
        ("first", "primero", "premier", "erste", "primo"),
        ("final", "final", "final", "endlich", "finale"),
        ("whole", "entero", "entier", "ganz", "intero"),
        ("single", "único", "seul", "einzig", "singolo"),
        ("human", "humano", "humain", "menschlich", "umano"),
        ("dear", "querido", "cher", "lieb", "caro"),
        ("beloved", "amado", "bien-aimé", "geliebte", "amato"),
        ("ancient", "antiguo", "ancien", "alt", "antico"),
        ("eternal", "eterno", "éternel", "ewig", "eterno"),
        ("endless", "sin fin", "sans fin", "endlos", "senza fine"),
        ("sudden", "repentino", "soudain", "plötzlich", "improvviso"),
        ("slow", "lento", "lent", "langsam", "lento"),
        ("quick", "rápido", "rapide", "schnell", "rapido"),
        ("ready", "listo", "prêt", "bereit", "pronto"),
        ("able", "capaz", "capable", "fähig", "capace"),
        ("better", "mejor", "meilleur", "besser", "migliore"),
        ("best", "el mejor", "le meilleur", "beste", "il migliore"),
        ("worse", "peor", "pire", "schlechter", "peggiore"),
        ("worst", "el peor", "le pire", "schlimmste", "il peggiore"),
        ("like", "como", "comme", "wie", "come"),
        ("well", "bien", "bien", "gut", "bene"),
        ("back", "atrás", "en arrière", "zurück", "indietro"),
        ("away", "lejos", "loin", "weg", "via"),
        ("together", "juntos", "ensemble", "zusammen", "insieme"),
        ("apart", "aparte", "à part", "auseinander", "a parte"),
        ("perhaps", "quizá", "peut-être", "vielleicht", "forse"),
        ("maybe", "tal vez", "peut-être", "vielleicht", "forse"),
        ("almost", "casi", "presque", "fast", "quasi"),
        ("enough", "suficiente", "assez", "genug", "abbastanza"),
        ("indeed", "en verdad", "en effet", "in der Tat", "davvero"),
        ("thus", "así", "ainsi", "so", "così"),
        ("therefore", "por lo tanto", "donc", "daher", "pertanto"),
        ("however", "sin embargo", "cependant", "jedoch", "tuttavia"),
        ("instead", "en cambio", "au lieu", "stattdessen", "invece"),
        ("else", "más", "sinon", "sonst", "altro"),
        ("once", "una vez", "une fois", "einmal", "una volta"),
        ("art", "eres", "es", "bist", "sei"),
        ("thou", "tú", "tu", "du", "tu"),
        ("thee", "ti", "toi", "dich", "te"),
        ("thy", "tu", "ton", "dein", "tuo"),
        ("thine", "tuyo", "tien", "dein", "tuo"),
        ("ye", "vosotros", "vous", "ihr", "voi"),
        ("hath", "tiene", "a", "hat", "ha"),
        ("doth", "hace", "fait", "tut", "fa"),
        ("dost", "haces", "fais", "tust", "fai"),
        ("shalt", "debes", "dois", "sollst", "devi"),
        ("wilt", "harás", "feras", "wirst", "farai"),
        ("wherefore", "por qué", "pourquoi", "warum", "perché"),
        ("whence", "de dónde", "d'où", "woher", "da dove"),
        ("whither", "adónde", "où", "wohin", "dove"),
        ("ere", "antes", "avant", "ehe", "prima"),
        ("unto", "a", "à", "zu", "a"),
        ("amongst", "entre", "parmi", "unter", "tra"),
        ("whilst", "mientras", "pendant que", "während", "mentre"),
        ("o'er", "sobre", "sur", "über", "sopra"),
        ("tis", "es", "c'est", "es ist", "è"),
        ("'tis", "es", "c'est", "es ist", "è"),
        ("cannot", "no puede", "ne peut pas", "kann nicht", "non può"),
        ("acknowledge", "reconocer", "reconnaître", "anerkennen", "riconoscere"),
        ("acknowledged", "reconocido", "reconnu", "anerkannt", "riconosciuto"),
        ("universally", "universalmente", "universellement", "allgemein", "universalmente"),
        ("possession", "posesión", "possession", "Besitz", "possesso"),
        ("wife", "esposa", "épouse", "Frau", "moglie"),
        ("husband", "esposo", "époux", "Mann", "marito"),
        ("family", "familia", "famille", "Familie", "famiglia"),
        ("families", "familias", "familles", "Familien", "famiglie"),
        ("alike", "iguales", "semblables", "gleich", "uguali"),
        ("happy", "feliz", "heureux", "glücklich", "felice"),
        ("unhappy", "infeliz", "malheureux", "unglücklich", "infelice"),
        ("hole", "agujero", "trou", "Loch", "buco"),
        ("ground", "suelo", "sol", "Boden", "terra"),
        ("hobbit", "hobbit", "hobbit", "Hobbit", "hobbit"),
        ("call", "llama", "appelle", "rufe", "chiama"),
        ("ishmael", "Ismael", "Ismaël", "Ismael", "Ismaele"),
        ("stage", "escenario", "scène", "Bühne", "palcoscenico"),
        ("players", "actores", "acteurs", "Spieler", "attori"),
        ("merely", "meramente", "simplement", "bloß", "soltanto"),
        ("poor", "pobre", "pauvre", "arm", "povero"),
        ("player", "actor", "acteur", "Spieler", "attore"),
        ("exits", "salidas", "sorties", "Abgänge", "uscite"),
        ("entrances", "entradas", "entrées", "Auftritte", "entrate"),
        ("parts", "papeles", "rôles", "Rollen", "parti"),
        ("age", "edad", "âge", "Alter", "età"),
        ("winter", "invierno", "hiver", "Winter", "inverno"),
        ("summer", "verano", "été", "Sommer", "estate"),
        ("spring", "primavera", "printemps", "Frühling", "primavera"),
        ("autumn", "otoño", "automne", "Herbst", "autunno"),
        ("season", "estación", "saison", "Jahreszeit", "stagione"),
        ("hour", "hora", "heure", "Stunde", "ora"),
        ("moment", "momento", "moment", "Augenblick", "momento"),
        ("year", "año", "année", "Jahr", "anno"),
        ("years", "años", "années", "Jahre", "anni"),
        ("future", "futuro", "avenir", "Zukunft", "futuro"),
        ("past", "pasado", "passé", "Vergangenheit", "passato"),
        ("present", "presente", "présent", "Gegenwart", "presente"),
        ("beginning", "comienzo", "commencement", "Anfang", "inizio"),
        ("end", "fin", "fin", "Ende", "fine"),
        ("thing", "cosa", "chose", "Ding", "cosa"),
        ("things", "cosas", "choses", "Dinge", "cose"),
        ("matter", "asunto", "affaire", "Sache", "faccenda"),
        ("question", "pregunta", "question", "Frage", "domanda"),
        ("reason", "razón", "raison", "Grund", "ragione"),
        ("cause", "causa", "cause", "Ursache", "causa"),
        ("meaning", "significado", "sens", "Bedeutung", "significato"),
        ("sense", "sentido", "sens", "Sinn", "senso"),
        ("spirit", "espíritu", "esprit", "Geist", "spirito"),
        ("ghost", "fantasma", "fantôme", "Geist", "fantasma"),
        ("god", "dios", "dieu", "Gott", "dio"),
        ("gods", "dioses", "dieux", "Götter", "dei"),
        ("angel", "ángel", "ange", "Engel", "angelo"),
        ("devil", "diablo", "diable", "Teufel", "diavolo"),
        ("hell", "infierno", "enfer", "Hölle", "inferno"),
        ("grace", "gracia", "grâce", "Gnade", "grazia"),
        ("mercy", "misericordia", "miséricorde", "Barmherzigkeit", "misericordia"),
        ("sin", "pecado", "péché", "Sünde", "peccato"),
        ("virtue", "virtud", "vertu", "Tugend", "virtù"),
        ("vice", "vicio", "vice", "Laster", "vizio"),
        ("faith", "fe", "foi", "Glaube", "fede"),
        ("doubt", "duda", "doute", "Zweifel", "dubbio"),
        ("trust", "confianza", "confiance", "Vertrauen", "fiducia"),
        ("promise", "promesa", "promesse", "Versprechen", "promessa"),
        ("oath", "juramento", "serment", "Eid", "giuramento"),
        ("law", "ley", "loi", "Gesetz", "legge"),
        ("order", "orden", "ordre", "Ordnung", "ordine"),
        ("chaos", "caos", "chaos", "Chaos", "caos"),
        ("battle", "batalla", "bataille", "Schlacht", "battaglia"),
        ("sword", "espada", "épée", "Schwert", "spada"),
        ("shield", "escudo", "bouclier", "Schild", "scudo"),
        ("crown", "corona", "couronne", "Krone", "corona"),
        ("throne", "trono", "trône", "Thron", "trono"),
        ("castle", "castillo", "château", "Burg", "castello"),
        ("wall", "muro", "mur", "Mauer", "muro"),
        ("bridge", "puente", "pont", "Brücke", "ponte"),
        ("river", "río", "rivière", "Fluss", "fiume"),
        ("mountain", "montaña", "montagne", "Berg", "montagna"),
        ("forest", "bosque", "forêt", "Wald", "foresta"),
        ("field", "campo", "champ", "Feld", "campo"),
        ("gold", "oro", "or", "Gold", "oro"),
        ("silver", "plata", "argent", "Silber", "argento"),
        ("iron", "hierro", "fer", "Eisen", "ferro"),
        ("glass", "vidrio", "verre", "Glas", "vetro"),
        ("mirror", "espejo", "miroir", "Spiegel", "specchio"),
        ("paper", "papel", "papier", "Papier", "carta"),
        ("ink", "tinta", "encre", "Tinte", "inchiostro"),
        ("pen", "pluma", "plume", "Feder", "penna"),
        ("chapter", "capítulo", "chapitre", "Kapitel", "capitolo"),
        ("line", "línea", "ligne", "Zeile", "riga"),
        ("quote", "cita", "citation", "Zitat", "citazione"),
        ("author", "autor", "auteur", "Autor", "autore"),
        ("reader", "lector", "lecteur", "Leser", "lettore"),
        ("poet", "poeta", "poète", "Dichter", "poeta"),
        ("poem", "poema", "poème", "Gedicht", "poesia"),
        ("verse", "verso", "vers", "Vers", "verso"),
        ("language", "lengua", "langue", "Sprache", "lingua"),
        ("tongue", "lengua", "langue", "Zunge", "lingua")
    ]
}
